### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by TondenOckay** [tinygiant98/nui#1]
It would be nice if this could be limited to work with only the armor parts a character has on their character.

So if they have the Gladiator right shoulder pad then it would allow them to put that part on and take off the part it replaces and put that part into the characters inventory. 

Maybe a player could find the Gladiator right shoulder pad it could be used for any race/sex or it might only be able to be used for races X, Y, and Z.

It would be nice if it could be limited to class, maybe take into account for light, medium, and heavy armor?

The idea would be to set these armor parts out in the world, on creatures, in chests, ruins and so on that players could find to sell, trade, or use on their own characters armor

So have it work like it does in other games when players find new armor parts, if it fits their race, or class, or level

**Comment by tinygiant98** [comment]
This would be a highly customized version of the appearance editor.  Once all the bugs are worked out of the basic system and a few more features are added, I'll see about adding filter/functionality to accomplish this.

**Comment by TondenOckay** [comment]
**Dye System**
What about a dye system that could be turned on or off. If turned on dyes are needed to change the color on an item? Once the dye is used it is removed from the players inventory. This would add more of an RP element to changing the color on armor and weapons as well as giving another thing for players to find, buy, sell, and create.

**Comment by tinygiant98** [comment]
@TondenOckay Not sure if that's within the scope of the basic form, but please set it up as a separate issue and we can take a look when the time comes.
