### ISSUE TITLE
Siala Requested Changes/Enhancements

### ISSUE THREAD

**Issue by tinygiant98** [tinygiant98/nui#6]
Pulled from Discord chat

- [x] Add weapons modification/coloring functionality
- [x] Add shield modification/coloring functionality
- [ ] Modify loading notes to include instruction count change instructions
- [x] Add loading form or conversation to demo module
- [ ] Check for player minor version to ensure they're running a game version that supports nui
- [x] Allow form to be collapsed
- [ ] Add a custom filtering function that the module owner can modify to filter (blacklist/whitelist) specific models
- [x] Allow previous/next to skip over unequipable models, or, filter out unequipable models
- [x] Research tattoo models versus normal appearance models
- [x] Pair left/right parts in the part category listbox instead of all right/all left together
- [x] Explore using targeting mode to select an equipped item from the inventory window instead of using the dropdown at the top of the form
- [ ] Add basic items to test module for users to use for modification
- [x] Suppress error message caused by closing data load form
- [x] Combine form loading sections and add "all types" option to combo
- [x] Allow previous/next to advance past first/last value
- [x] Add color selected indicator over color palette

**Comment by eveferon** [comment]
I would give "Research tattoo models versus normal appearance models" lower prio. I do not think, it is an important thing. When everything is finished - one could add it then

**Comment by tinygiant98** [comment]
Sounds good.  The list is not prioritized, just the list as I pulled it from the discord chat.  I'll start working big picture stuff first.

**Comment by eveferon** [comment]
How about  "add a helmet, cloths, light, medium, heavy armor, shield, sword on the floor of the testing area"?

**Comment by tinygiant98** [comment]
> How about "add a helmet, cloths, light, medium, heavy armor, shield, sword on the floor of the testing area"?

Added.

**Comment by eveferon** [comment]
Opening editor results in already collapsed view. We should set collapsed to FALSE for the collabsed bind 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/4124903/140502231-bec03f31-e05b-42d7-b650-7049f5044c56.png">

**Comment by eveferon** [comment]
Opening editor after loading results in this error 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/4124903/140502296-4d7b12fa-fa60-47cc-8e63-b606ba2074ff.png">

and I cannot see the models in the equipment section

<img width="547" alt="image" src="https://user-images.githubusercontent.com/4124903/140502398-d1cd2ed9-dfe7-4d66-b0f5-6add6bbaaace.png">

**Comment by tinygiant98** [comment]
Yes, when I sent the demo module, I mentioned that the data wasn't hooked up yet, as I ran out of time last night.  I know what's causing that error, but it's not an issue, just an unforeseen report due to the additional functionality being added. I'll suppress it.

**Comment by eveferon** [comment]
One more suggestion. How about we add parameters to the call for opening the form where we can signalize for instance if we want to have appearance editor or not something like (int nAppearanceEditor = TRUE, int nEqipmentEditor = TRUE) so default way is to keep showing both but one could say I want to have only appearance editor or equipment editor. That would be really nice. Actually maybe one could allow to filter armor, helmet or weapons too. Then it would be super nice and we will have the best from both ideas (item selector and combined views). If someone only set TRUE for nWeaponEditor then nothing else is simply displayed in the form. Is it a good idea?
